name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3

      - name: Деплой на GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

      - name: Опубликовать сайт
        uses: actions/deploy-pages@v1
