name: Keep Backend Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # каждые 10 минут

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping backend
        run: curl -s https://your-render-backend.onrender.com/
